# Generated by Django 5.1.15 on 2026-09-16 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.clientcompany'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='permitted_entities',
            field=models.ManyToManyField(blank=True, help_text='Only used for Client Entity Users.', related_name='permitted_users', to='tenancy.legalentity'),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.supplier'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='accepted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.clientcompany'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='entities',
            field=models.ManyToManyField(blank=True, to='tenancy.legalentity'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_user_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.supplier'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_company__isnull', True), ('role', 'sz_admin'), ('supplier__isnull', True)), models.Q(('client_company__isnull', False), ('role__in', ('client_admin', 'client_entity_user')), ('supplier__isnull', True)), models.Q(('client_company__isnull', True), ('role__in', ('supplier_admin', 'supplier_user')), ('supplier__isnull', False)), _connector='OR'), name='user_role_matches_tenant'),
        ),
        migrations.AddConstraint(
            model_name='userinvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_company__isnull', False), ('role__in', ('client_admin', 'client_entity_user')), ('supplier__isnull', True)), models.Q(('client_company__isnull', True), ('role__in', ('supplier_admin', 'supplier_user')), ('supplier__isnull', False)), _connector='OR'), name='user_invite_one_tenant'),
        ),
    ]
