# Generated by Django 5.1.15 on 2026-09-16 15:39

import apps.core.models
import apps.supply.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The farm, forest owner, plantation or company that produced the raw material. This may be different from your own company.', max_length=200, verbose_name='Producer name')),
                ('country', apps.core.models.CountryField(help_text='Country where this producer operates.', max_length=2)),
                ('address', models.TextField(blank=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business or forestry licence registration, if known.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.supplier')),
                ('suppliers', models.ManyToManyField(help_text='Suppliers that source from this producer.', related_name='producers', to='tenancy.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('product_code', models.CharField(blank=True, max_length=64)),
                ('sku', models.CharField(blank=True, help_text='Your stock keeping unit code, if you use one.', max_length=64, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('commodity', models.CharField(choices=[('cattle', 'Cattle'), ('cocoa', 'Cocoa'), ('coffee', 'Coffee'), ('oil_palm', 'Oil palm'), ('rubber', 'Rubber'), ('soya', 'Soya'), ('wood', 'Wood')], help_text='The EUDR raw material this product contains or is made from.', max_length=16)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonised System code (6 digits), usually on your customs or export paperwork. Example: 4407 91 for sawn oak.', max_length=12, verbose_name='HS code')),
                ('cn_code', models.CharField(blank=True, help_text='EU Combined Nomenclature code (8 digits). Example: 4407 91 15.', max_length=12, verbose_name='CN code')),
                ('material', models.CharField(blank=True, help_text='Example: solid oak, plywood, cocoa butter.', max_length=120)),
                ('species_common', models.CharField(blank=True, help_text='Required for wood. Example: European oak.', max_length=120, verbose_name='Species (common name)')),
                ('species_scientific', models.CharField(blank=True, help_text='Latin name. Example: Quercus robur. Ask the sawmill or producer if unsure.', max_length=120, verbose_name='Scientific species name')),
                ('country_of_production', apps.core.models.CountryField(blank=True, help_text='Where the raw material was grown or harvested — not where the product was manufactured.', max_length=2)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('t', 'Tonnes (t)'), ('m3', 'Cubic metres (m³)'), ('pcs', 'Pieces'), ('head', 'Head (cattle)')], default='kg', max_length=8)),
                ('clients', models.ManyToManyField(help_text='Which of your customers can see this product. Other customers will not see it.', related_name='shared_products', to='tenancy.clientcompany')),
                ('producers', models.ManyToManyField(blank=True, related_name='products', to='supply.producer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tenancy.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourcePlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A name you will recognise. Example: North block, Hofmann forest.', max_length=200, verbose_name='Source name')),
                ('plot_reference', models.CharField(blank=True, help_text='Land registry, concession or forest compartment reference, if any.', max_length=100)),
                ('country', apps.core.models.CountryField(help_text='Country where the land is located.', max_length=2)),
                ('production_start', models.DateField(blank=True, null=True)),
                ('production_end', models.DateField(blank=True, null=True)),
                ('harvest_start', models.DateField(blank=True, null=True)),
                ('harvest_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Area (ha)')),
                ('geometry_source', models.CharField(blank=True, choices=[('drawn', 'Drawn on map'), ('uploaded', 'Uploaded / pasted GeoJSON'), ('coordinates', 'Entered coordinates')], max_length=16)),
                ('geometry_updated_at', models.DateTimeField(blank=True, null=True)),
                ('clients', models.ManyToManyField(help_text='Which of your customers can see this location.', related_name='shared_source_plots', to='tenancy.clientcompany')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_plots', to='supply.producer')),
                ('products', models.ManyToManyField(blank=True, related_name='source_plots', to='supply.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_plots', to='tenancy.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.supply.models.evidence_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('origin', 'Origin / harvesting evidence'), ('legality', 'Legality (permits, licences, concessions)'), ('product', 'Product specification'), ('producer', 'Producer registration'), ('geospatial', 'Geospatial file'), ('other', 'Other supporting document')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='tenancy.supplier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='supply.producer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='supply.product')),
                ('source_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='supply.sourceplot')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('supplier', 'sku'), name='product_unique_sku_per_supplier'),
        ),
        migrations.AddIndex(
            model_name='sourceplot',
            index=models.Index(fields=['plot_reference'], name='supply_sour_plot_re_13bc76_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceplot',
            constraint=models.CheckConstraint(condition=models.Q(('geometry__isnull', False), ('point__isnull', False), _connector='OR'), name='plot_has_location'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('producer__isnull', False), ('source_plot__isnull', False), _connector='OR'), name='evidence_attached_to_record'),
        ),
    ]
