# Generated by Django 5.1.15 on 2026-09-16 15:39

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Supplier company name')),
                ('country', apps.core.models.CountryField(max_length=2)),
                ('address', models.TextField()),
                ('company_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=32, verbose_name='VAT number')),
                ('eori_number', models.CharField(blank=True, help_text='Where applicable.', max_length=32, verbose_name='EORI number')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('eudr_contact_name', models.CharField(blank=True, help_text='The person who can answer questions about product origin.', max_length=150, verbose_name='EUDR contact name')),
                ('eudr_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='EUDR contact email')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('suspended', 'Suspended')], default='registered', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Company name')),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('country', apps.core.models.CountryField(max_length=2)),
                ('address', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=32, verbose_name='VAT number')),
                ('eori_number', models.CharField(blank=True, help_text='Where applicable (EU customs identifier).', max_length=32, verbose_name='EORI number')),
                ('company_size', models.CharField(blank=True, choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=16)),
                ('main_contact_name', models.CharField(max_length=150)),
                ('main_contact_email', models.EmailField(max_length=254)),
                ('main_contact_phone', models.CharField(blank=True, max_length=40)),
                ('eudr_contact_name', models.CharField(blank=True, max_length=150, verbose_name='EUDR contact name')),
                ('eudr_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='EUDR contact email')),
                ('eudr_contact_phone', models.CharField(blank=True, max_length=40, verbose_name='EUDR contact phone')),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended')], default='onboarding', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'client companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Entity name')),
                ('country', apps.core.models.CountryField(max_length=2)),
                ('address', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=64, verbose_name='Company registration number')),
                ('vat_number', models.CharField(blank=True, max_length=32, verbose_name='VAT number')),
                ('eori_number', models.CharField(blank=True, max_length=32, verbose_name='EORI number')),
                ('eudr_role', models.CharField(choices=[('operator', 'Operator'), ('trader_sme', 'Trader (SME)'), ('trader_non_sme', 'Trader (non-SME)'), ('downstream_operator', 'Downstream operator'), ('not_determined', 'Not yet determined')], default='not_determined', max_length=32, verbose_name='EUDR role')),
                ('traces_operator_reference', models.CharField(blank=True, help_text='Recorded manually. No TRACES integration is connected.', max_length=64, verbose_name='TRACES registration reference')),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='tenancy.clientcompany')),
            ],
            options={
                'verbose_name_plural': 'legal entities',
                'ordering': ['client__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='tenancy.clientcompany')),
                ('entities', models.ManyToManyField(blank=True, help_text='Legal entities that buy from this supplier.', related_name='supplier_links', to='tenancy.legalentity')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='tenancy.supplier')),
            ],
            options={
                'ordering': ['client__name', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('country', apps.core.models.CountryField(max_length=2)),
                ('address', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='tenancy.supplier')),
            ],
            options={
                'verbose_name_plural': 'supplier factories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.supplier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invitations', to='tenancy.clientcompany')),
                ('entities', models.ManyToManyField(blank=True, to='tenancy.legalentity')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='entity_unique_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='supplierclientlink',
            constraint=models.UniqueConstraint(fields=('supplier', 'client'), name='supplier_client_unique'),
        ),
    ]
